// react-calc/src/App.js
import logo from './logo.svg';
import './App.css';
import Boton from './componentes/Boton';
import Pantalla from './componentes/Pantalla';
import BotonClear from './componentes/BotonClear';
import { useState } from 'react'
import { evaluate } from 'mathjs';

function App() {
  const [input, setIntup] = useState('');

  const agregarInput = val => {
    setIntup(input + val);
  };

  const calcularResultado = () => {
    if (input)
      setIntup(evaluate(input));
  };

  return (
    <div className="App">
      <div className='calculadora'>
        <Pantalla input={input} />

        <div className='fila'>
          <Boton manejarClic={agregarInput}>1</Boton>
          <Boton manejarClic={agregarInput}>2</Boton>
          <Boton manejarClic={agregarInput}>3</Boton>
          <Boton manejarClic={agregarInput}>+</Boton>
        </div>
        <div className='fila'>
          <Boton manejarClic={agregarInput}>4</Boton>
          <Boton manejarClic={agregarInput}>5</Boton>
          <Boton manejarClic={agregarInput}>6</Boton>
          <Boton manejarClic={agregarInput}>-</Boton>
        </div>
        <div className='fila'>
          <Boton manejarClic={agregarInput}>7</Boton>
          <Boton manejarClic={agregarInput}>8</Boton>
          <Boton manejarClic={agregarInput}>9</Boton>
          <Boton manejarClic={agregarInput}>*</Boton>
        </div>
        <div className='fila'>
          <Boton manejarClic={calcularResultado}>=</Boton>
          <Boton manejarClic={agregarInput}>0</Boton>
          <Boton manejarClic={agregarInput}>.</Boton>
          <Boton manejarClic={agregarInput}>/</Boton>
        </div>
        <div className='fila'>
          <BotonClear manejarClear={() => setIntup('')}>
            Limpiar
          </BotonClear>
        </div>
      </div>
    </div>
  );
}

export default App;

// angular-calc/src/app/app.component.ts
import { Component } from '@angular/core';
import { evaluate } from 'mathjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  //title = 'angular-calc';
  input: string = "";

  setInput(dato: string){
    this.input += dato;
  }

  calcular(){
    if(this.input)
      this.input = evaluate(this.input);
  }
}

<div class = "calculadora">
  <app-pantalla [input] = input></app-pantalla>

  <div class = 'fila'>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>1</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>2</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>3</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>+</p></app-boton>
  </div>

  <div class = 'fila'>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>4</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>5</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>6</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>-</p></app-boton>
  </div>

  <div class = 'fila'>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>7</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>8</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>9</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>*</p></app-boton>
  </div>

  <div class = 'fila'>
    <app-boton (manejarClic) = "calcular()"><p #c>=</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>0</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>.</p></app-boton>
    <app-boton (manejarClic) = "setInput($any($event))"><p #c>/</p></app-boton>
  </div>

  <div class = 'fila'>
    <app-boton-clear (manejarClear) = "input = ''"></app-boton-clear>
  </div>


</div>
